const MAX_PDF_BYTES = 5 * 1024 * 1024;
const MAX_PDF_PAGES = 4;
const MIN_EXTRACTED_CHARS = 150;
const MAX_EXTRACTED_CHARS = 25000;
const MAX_EXPERIENCE_ITEMS = 15;
const MAX_PROJECT_ITEMS = 10;
const MAX_SKILLS = 40;
const MAX_EDUCATION_ITEMS = 10;
const MAX_CERTIFICATIONS = 15;
const MAX_LANGUAGES = 15;

module.exports = {
  MAX_PDF_BYTES,
  MAX_PDF_PAGES,
  MIN_EXTRACTED_CHARS,
  MAX_EXTRACTED_CHARS,
  MAX_EXPERIENCE_ITEMS,
  MAX_PROJECT_ITEMS,
  MAX_SKILLS,
  MAX_EDUCATION_ITEMS,
  MAX_CERTIFICATIONS,
  MAX_LANGUAGES,
};
